Brainrake day01
Smorci/100-Days-Of-Rust pull request #7
Opened 2024-02-21 09:09 UTC by brainrake

Solution to Week01/Day01

2024-02-21 20:46 UTC, Smorci requested changes
Structured and nice

2024-02-21 20:46 UTC, Smorci commented on Week-01/Day-01_Convert-Ages-To-Days/convert_ages_to_days_brainrake/src/bin/web.rs
Very cool, but it is not part of the requirement, please remove. With that also remove dependencies please.

2024-02-21 20:46 UTC, Smorci commented on Week-01/Day-01_Convert-Ages-To-Days/convert_ages_to_days_brainrake/index.html
Very cool, but it is not part of the requirement, please remove.

2024-02-21 20:46 UTC, Smorci commented on Week-01/Day-01_Convert-Ages-To-Days/convert_ages_to_days_brainrake/src/lib.rs
> +    fn test_0() {
Same applies here as in [this PR comment](https://github.com/Smorci/100-Days-Of-Rust/pull/4/files#r1498273676)

2024-02-21 20:46 UTC, Smorci commented on Week-01/Day-01_Convert-Ages-To-Days/convert_ages_to_days_brainrake/README.md
Like the README, nice. We should make a template for creating cargo packages.

2024-02-23 13:36 UTC, brainrake commented on Week-01/Day-01_Convert-Ages-To-Days/convert_ages_to_days_brainrake/src/bin/web.rs
This is test code and development tooling, not part of the application functionality. The deps should be dev-dependencies, but I couldn't get it to run that way. Maybe I can move it to an [example](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#examples) which has separate deps iirc.

2024-02-23 13:36 UTC, brainrake commented on Week-01/Day-01_Convert-Ages-To-Days/convert_ages_to_days_brainrake/index.html
As above.

2024-02-23 13:36 UTC, brainrake commented on Week-01/Day-01_Convert-Ages-To-Days/convert_ages_to_days_brainrake/src/lib.rs
> +    fn test_0() {
Same response.

2024-02-23 13:36 UTC, brainrake commented on Week-01/Day-01_Convert-Ages-To-Days/convert_ages_to_days_brainrake/README.md
:+1:

2024-02-23 14:01 UTC, brainrake commented on Week-01/Day-01_Convert-Ages-To-Days/convert_ages_to_days_brainrake/src/main.rs
> +fn main() {
maybe this should be a cargo `example` too, pending discussion on slack

2024-02-26 19:54 UTC, Smorci approved these changes

2024-02-26 21:23 UTC, brainrake commented on Week-01/Day-01_Convert-Ages-To-Days/convert_ages_to_days_brainrake/src/main.rs
> +fn main() {
decided against it, this is fine

2024-02-26 21:23 UTC, brainrake commented on Week-01/Day-01_Convert-Ages-To-Days/convert_ages_to_days_brainrake/index.html
Didn't fix it yet.

2024-02-26 21:23 UTC, brainrake commented on Week-01/Day-01_Convert-Ages-To-Days/convert_ages_to_days_brainrake/src/bin/web.rs
Didn't fix it yet

2024-02-28 00:11 UTC, botiboti approved these changes
nice, I like how clean it is

2024-03-03 02:13 UTC, brainrake commented on Week-01/Day-01_Convert-Ages-To-Days/convert_ages_to_days_brainrake/src/bin/web.rs
Moved to `examples/web/`.

2024-03-03 02:13 UTC, brainrake commented on Week-01/Day-01_Convert-Ages-To-Days/convert_ages_to_days_brainrake/index.html
Moved to `examples/web/`.

2024-03-03 02:14 UTC, merged